import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossorigin="anonymous"
        />
        <link rel="stylesheet" href="../styles/style.scss"/>
      </Head>

      <section id="welcome">
        <div className="welcome-menu">
          <div className="logo">
            <img
              src="https://image.similarpng.com/very-thumbnail/2020/06/Restaurant-logo-with-chef-drawing-template-on-transparent-background-PNG.png"
            />
          </div>
          <div className="menu">
            <div className="menu-title">home</div>
            <ul className="links">
              <li>
                <a className="menu-link" href="#menu">
                  Menu <i class="fa fa-hamburger"></i>
                </a>
              </li>
              <li>
                <a className="info-link" href="#information">
                  Information <i className="fa fa-info" aria-hidden="true"></i>
                </a>
              </li>
              <li>
                <a className="review-link" href="#reviews">
                  Reviews <i className="fas fa-comment"></i>
                </a>
              </li>
            </ul>
          </div>
          {/* <hr className="white-line"/> */}
        </div>
        <div className="welcome-jumbo">
        <div className="burger-title">
            <div className="status">new</div>
            <h1>World's Famous Ring Burger</h1>
          </div>
          <img
            className="burger"
            src="https://waybackburgers.com/wp-content/uploads/Rodeo_Large.jpg"
          />
          
        </div>
      </section>
      <section id="information">
        <div className="restaurant-img">
          <img src="https://images.pexels.com/photos/239975/pexels-photo-239975.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
        </div>
        <div className="info">
          <h2> We Started from the Bottom in 1987</h2>
          <div className="paragraphs">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </div>
          <a className="link" href="#">
            Link to more restaurants
            <div className="circle-right">
              <i className="fa fa-chevron-right" aria-hidden="true"></i>
            </div>
          </a>
          <div className="backToTop">
            <a href="#welcome">Back To Top</a>
          </div>
        </div>
      </section>
      <section id="menu">
        <div className="menu-title">
          <h1>We have everything you need to kill your hunger</h1>
        </div>
        <div className="menu-btn">
          <a href="#">View Our Menu</a>
        </div>
        <div className="food-slider">
          {/* Beef */}
          <div className="slide">
            <div className="background"></div>
            <div className="content">
              <div className="food-title">Beef</div>
              <p className="food-description">
                All of our Beef items including Burgers, Ribs and Steaks
              </p>
              <img
                className="beef-img"
                src="https://www.deliciousmagazine.co.uk/wp-content/uploads/2018/09/905610-1-eng-GB_burger-768x960.jpg"
              />
            </div>
          </div>
          {/* Chicken */}
          <div className="slide">
            <div className="background"></div>
            <div className="content">
              <div className="food-title">Chicken</div>
              <p className="food-description">
                All chicken items include Burgers, Meals and Pasta
              </p>
              <img
                className="chicken-img"
                src="https://img.taste.com.au/KWJWF7T0/w1200-h630-cfill/taste/2018/06/july-18_lemongrass-and-chilli-chicken-138895-1.jpg"
              />
            </div>
          </div>
          {/* Salads */}
          <div className="slide">
            <div className="background"></div>
            <div className="content">
              <div className="food-title">Salads</div>
              <p className="food-description">
                Filling and Healthy Salads with home made dressing
              </p>
              <img
                className="salad-img"
                src="https://www.twopeasandtheirpod.com/wp-content/uploads/2019/06/Easy-Green-Salad-4-500x500.jpg"
              />
            </div>
          </div>
          {/* Pasta */}
          <div className="slide">
            <div className="background"></div>
            <div className="content">
              <div className="food-title">Pasta</div>
              <p className="food-description">
                Delicious pasta with home made sauce
              </p>
              <img
                className="pasta-img"
                src="https://media.istockphoto.com/photos/pasta-with-meat-tomato-sauce-and-vegetables-picture-id857927726?k=20&m=857927726&s=612x612&w=0&h=7PRPPuKWStSob7flmCsIeez8oQRqMFGQfVv4wdBxZ5U="
              />
            </div>
          </div>
          {/* Dessert */}
          <div className="slide">
            <div className="background"></div>
            <div className="content">
              <div className="food-title">Desserts</div>
              <p className="food-description">
                All of our Beef items including Burgers, Ribs and Steaks
              </p>
              <img
                className="dessert-img"
                src="https://www.eatthis.com/wp-content/uploads/sites/4/2020/10/pizookie-trio.jpg"
              />
            </div>
          </div>
        </div>
      </section>
      <section id="reviews">
        <div className="background">
          <div className="reviews-title">
            <h1>reviews</h1>
          </div>
          <div className="review-comment">
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                  Really FANTASTIC!!! If I could give 10 stars, I would. Nice,
                  cosy place. Very friendly staff (English speaking, was no
                  problem for us). The food was really phenomenal, especially the
                  chicken with honey. To be repeated!
                </p>
                <p className="review-user"> Warsha J</p>
              </div>
            </div>
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                  Visited by chance because another restaurant was closed....
                  Fortunately, that other restaurant was closed, because that
                  would definitely have been more disappointing than La
                  Barraca. <br/>Delicious food, nice service, neat interior. It was all
                  just right.
                </p>
                <p className="review-user"> Pascal Huntjens</p>
              </div>
            </div>
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                Delicious food again at MT Olympus. At the moment, this is the best tapas restaurant in Maastricht. Original, special, fine flavours and super-fresh products! Nice wines, delicious coffee, imaginative cocktails!

                Fine service, young but knowledgeable and warm! The prices are not low, but you get something for it!
                </p>
                <p className="review-user">Roger Hagenaars</p>
              </div>
            </div>
          </div>
          <div className="review-comment">
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                  Really FANTASTIC!!! If I could give 10 stars, I would. Nice,
                  cosy place. Very friendly staff (English speaking, was no
                  problem for us). The food was really phenomenal, especially the
                  chicken with honey. To be repeated!
                </p>
                <p className="review-user"> Warsha J</p>
              </div>
            </div>
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                  Really FANTASTIC!!! If I could give 10 stars, I would. Nice,
                  cosy place. Very friendly staff (English speaking, was no
                  problem for us). The food was really phenomenal, especially the
                  chicken with honey. To be repeated!
                </p>
                <p className="review-user"> Warsha J</p>
              </div>
            </div>
            <div className="comment">
              <div className="review-type">
                <h1>G</h1>
              </div>
              <div className="review-stars">
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
              </div>
              <div className="review-text">
                <p>
                  Really FANTASTIC!!! If I could give 10 stars, I would. Nice,
                  cosy place. Very friendly staff (English speaking, was no
                  problem for us). The food was really phenomenal, especially the
                  chicken with honey. To be repeated!
                </p>
                <p className="review-user"> Warsha J</p>
              </div>
            </div>
          </div>
          <div className="backToTop">
            <a href="#welcome">Back To Top</a>
          </div>
        </div>
      </section>

      <footer className="footer">
        <div className="store-info">
          <div className="contact">
            <h1>contact</h1>
            <p>randomeEmail@gmail.com</p>
            <div className="phone-number">
              <a href="tel:9874752938">987-475-2938</a>
            </div>
            <h1 className="book-btn">Direct Book</h1>
            <div className="address">
              584 Main street <br></br>
              New York, New york F5H 8B3
            </div>
            <h1 className="route">Route</h1>
          </div>
          <div className="store-hours">
            <div className="title">
              <h1>opening hours</h1>
              <h2>our kitchen closes at <em>11pm</em></h2>
            </div>

              <div className="weekdays">
                <p>Monday</p>
                <p>Tuesday</p>
                <p>Wednesday</p>
                <p>Thursday</p>
                <p>Friday</p>
                <p>Saturday</p>
                <p>Sunday</p>
              </div>
              <div className="hours">
                <p className="closed">CLOSED</p>
                <p className="closed">CLOSED</p>
                <p>10:00 - 11:00PM</p>
                <p>10:00 - 11:00PM</p>
                <p>9:30 - 1:00AM</p>
                <p>9:30 - 1:00AM</p>
                <p>10:00 - 11:00PM</p>
              </div>
          </div>
          <div className="follow">
            <h1>follow us</h1>
            <div className="social-icons">
            <a href="#">
              <i className="fab fa-facebook-f"></i>
            </a>
            <a href="#">
              <i className="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i className="fab fa-instagram"></i>
            </a>
          </div>
          </div>
        </div>
        <div className="backToTop">
          <a href="#welcome">Back To Top</a>
        </div>
      </footer>
    </div>
  );
}
